app/globals-custom.css, app/globals.css, app/layout.tsx, eslint.config.mjs, tailwind-custom.config.ts, tailwind.config.ts
fix #28
- shadcn 컴포넌트 install 시 tailwindcss 파일에서 플러그인 js 부분을 문자열로 자동 전환되는 이슈
- shadcn 컴포넌트 eslint prettier 규칙 무시
- 계속 shadcn 내부 코드까지 eslint 규칙을 적용시켜버려서 무시하게끔 수정했습니다
- shadcn에서는 import 시 기본적으로 tailwind.config.ts를 바라보기때문에 tailwind.config.ts를 shadcn base 유틸로 두고, 별도의 tailwind-custom.config.ts 파일을 생성하여, pxr 단위변환에 대한 내역을 shadcn에서 간섭하지 못하도록 구분하였습니다.
- globals.css 또한 같이 변경이 되어서 기존 커스텀 color의 간섭을 막기 위해, 별도의 globals-custom.css를 생성하여 커스텀 컬러만 모아서 작성해주었습니다.
- 테스트 결과
- pxr도 정상적으로 동작하고 shadcn 컴포넌트 중 tailwind.config.ts와 globalse.css을 변경하는 컴포넌트를 import 하였을 경우, 기존 커스텀 컬러에 간섭하지 않는 부분을 확인했습니다(선언 되어있는 컬러 한정)
- 만약 shadcn 컴포넌트 import 시 해당 pxr 플러그인과 스프레드 구문에 관섭이 발생한다면 @junghwa1996 저한테 이슈 전달 부탁드립니다.
=> shadcn 컴포넌트 install 시 tailwindcss 파일에서 플러그인 js 부분을 문자열로 자동 전환되는 이슈

hooks/useForm.ts
fix #67 
- useForm handleChange type update
- 이전에는 `useForm` 커스텀 훅에 `handleChange` 함수 타입이 `Input`만 설정이 되어있어서 `Textarea` 일때는 change이벤트가 발생하지않았습니다
- `TextArea` 타입 추가하여 정상작동 확인하였습니다
- `useForm` 에 대해 참고사항을 주석으로 추가했습니다
- 해당 훅을 사용하실 `input`과 `textarea`에는 서버로 전송될 `key name`이 작성되어있어야 합니다. `name`이 없을 경우 `handleChange`가 동작하지않습니다.
=> useForm hooks type update

app/globals-custom.css, components/TaskCard/KebabButton.tsx, components/TaskCard/TaskCard.tsx, stories/TaskCard.stories.tsx, types/taskCard.type.ts
close #66 
- 할 일 컴포넌트 Dropdown추가
- 스토리북에 할 일 컴포넌트 추가
- 이전 작업의 할 일 컴포넌트에 Dropdown 추가했습니다.
- 스토리북에 할 일 컴포넌트 추가했습니다.
---
Dropdown의 kebab icon 버튼의 경우 다른 페이지에서도 사용되는 부분이라 `global-custom.css` 파일에 `icon-kebab` 클래스로 스타일 추가하였습니다. 작업하실 떄 참고 부탁드립니다!
=> 할 일 카드 Dropdown, Storybook 추가

app/addteam/page.tsx, types/group.type.ts
close #76 
- 이미지 업로드 시 프리뷰 및 팀 생성하기 POST 시 이미지 url POST 
- 팀 생성하기 POST 기능 구현
- POST `respones`를 `user store`에 저장
- `addteam.tsx` 에 팀 생성하기 POST 구현 했습니다.
- 이미지 업로드 시 프리뷰로 노출되게 구현 했습니다.
- 팀 생성하기 submit 시 새로운 `FormData`를 생성합니다. 이미지 POST 먼저 진행 후 받은 `response`를 기존 `FormData`에 추가하여, 생성 POST 진행
- `createGroup POST` 시 `teamId`는 `response`에 포함되어있지않는데, store 업데이트 타입에는 `teamId`가 포함되어야하기때문에 받은 `response`에 `teamId`를 포함시켜서 store 업데이트 진행
- 로그인 > (팀 length가 0이어야 함) 로그인 후 메인으로 자동 리다이렉트 > 팀생성하기 UI 노출 > 팀 생성하기 클릭하여 `addteam`으로 이동 > 이미지와 팀 이름을 넣고 팀 생성하기 클릭 > 생성된 팀페이지로 이동
- https://github.com/fe11-part4-team3/coworkers/blob/69f5a9b933cc83c108a7ff5103da2c72a54ba065/app/addteam/page.tsx#L58-L66  여기 부분 @Woolegend 님 팀 수정하기 페이지에서도 동일하게 사용될 것 같아서 이미지를 넣으면 url로 변환해서 새로운 formData 생성하는 것 까지 포함된 커스텀 훅을 제작할지 고민중입니다 의견주세요 …
=> 팀 생성하기 기능 구현 및 store에 patch 

app/globals-custom.css, tailwind.config.ts
close #91 
- `globals-custom.css` 에 `:root -input `컬러 추가 (하드 컬러로 넣음, opacity X)
- `shadcn` `border-input` class에 커스텀 컬러로 변경
- 이슈 본문에 작성해두긴 했는데, 기존에 `input` `border`가 안보인다는 의견이 있어서 계속 살펴보니 시안이 opacity Inside로 들어가서(웹에서는 opcity가 있는 inside border는 코드적으로 좋지않으며, border 대신 box-shadow로 써야함) 맞지 않는 거였습니다.
- 이게 드롭다운이랑 셀렉트 `border`에는 영향이 없었던 이유는 서로 다른 디자이너분이 작업해주셨는지 해당 컴포넌트는 `Outside (--t-secondary) #334155` 로 작업이 되어서 영향이 없었던거였습니다....🥲
- `shadcn` `input` 컴포넌트를 사용 할 경우 `shadcn color`인 `border-input` 클래스가 붙게 됩니다. 그래서 `shadcn` `-input` 값을 제가 별도로 추가한 (하드하게 스포이드로 찍어서 나온 값) 컬러로 넣어두었습니다.
이게 디자이너 관점과 개발자 관점이 무척 상이한데요
[디자이너]
- 피그마에서 `opacity border`를 구현 시 `inside`로 들어가는게 맞긴 합니다.
- 이렇게 되면 사실상 `border`의 실제 차지하는 영역은 `0px` => 이유는? 피그마는 벡터 기반이라서 (일러스트와 동일)
- 만약 `outside`로 작업 할 경우 `border`의 `px`값을 먹이기위해서 `strok`를 …
=> input color 시안과 다름 이슈

hooks/useGroup.ts, stores/useGroup.stroe.ts
close #116 
경로상 현재 위한 그룹의 데이터 저장소와 이를 관리할 커스텀 훅을 구현합니다.
> 현재 경로가 `/1234` 혹은 `/1234/tasklist`일 때, 위치한 그룹은 `ID`가 `1234`인 그룹입니다.
`zustand`로 구현한 저장소입니다.
해당 저장소에 대한 설명은 스크립트 파일의 주석으로도 남겨져 있습니다.
**※사용법**
```ts
/**
* 현재 경로상 위치한 그룹(팀)과 관련된 데이터를 관리합니다.
*
* @name `group-store`
*
* @interface `IUseGroupStore`
* @property `group` : 현재 위치한 그룹(팀) 데이터
* @property `members` : 현제 그룹에 속한 멤버 목록 데이터
* @property `taskLists` : 현재 그룹에 속한 할 일 목록 배열 데이터
* @property `setGroup` : 그룹 데이터 설정 함수
* @property `setMembers` : 멤버 목록 데이터 설정 함수
* @property `settaskLists` : 할 일 목록 배열 설정 함수
* @property `clearStore` : 저장소에서 관리하는 데이터 `null`로 초기화
*/
```
현재 위치한 그룹의 데이터를 관리하기 위한 커스텀 훅입니다.
해당 훅은 `getGroup`으로 요청한 데이터를 관리합니다.
**사용법**
```ts
const { teamId } = usePatams();
const { ... } = useGroup(teamId);
```
해당 훅에 대한 설명은 스크립트 파일의 …
=> #116 그룹 데이터 저장소와 관리를 위한 커스텀 훅 구현

components/ArticleCommentTextarea/ArticleCommentTextarea.tsx, components/TaskCommentTextarea/TaskCommentTextarea.tsx, stories/ArticleCommentTextarea.stories.tsx, stories/CommentTextarea.stories.tsx, stories/TaskCommentTextarea.stories.tsx
close #118 
- 자유게시판 게시글 상세 댓글 입력 컴포넌트 작업
- 스토리북 추가
- 자유게시판 게시글 상세 페이지의 댓글 입력 컴포넌트 작업했습니다.
- 스토리북에서 확인 가능하십니다.
=> 자유게시판 게시글 상세 페이지 댓글 입력 textarea

app/login/page.tsx, app/reset-password/page.tsx, types/buttons.type.ts, types/inputField.type.ts
close #124 
- 로그인에서 '비밀번호를 잊으셨나요?' 클릭 시 임의 모달 만들어 초기화 메일 발송 기능 구현
- 이메일로 연결되는 `/reset-password` 페이지 생성
- 받은 토큰으로 비밀번호 초기화
- 버튼 이전 커밋 반영 내용 추가 (onClick 필수값에서 제외)
- InputField type 변경
- 로그인 페이지에서 `'비밀번호를 잊으셨나요?'` 클릭 시 모달(임의)이 열리면서 이메일 요청을 합니다. 이메일을 입력하시고 '링크 보내기' 클릭 시 해당 이메일로 비밀번호 초기화 메일이 전달 됩니다
> 꼭 이메일을 받을 수 있는 이메일을 입력 해주세요.
- 받은 메일 링크로 이동하면 토큰값이 담긴 `url`로 `reset-password` 페이지로 이동합니다. (현재는 `localhost:3000` 으로 되어있습니다)
- 변경할 비밀번호를 입력한 후 재설정 버튼을 누르면 변경 완료되었다는 alert과 함께 `/login` 페이지로 이동합니다.
- 추가로 `Buttons` 컴포넌트에 `props`를 이전 PR에서도 수정 했었는데 여기서도 필요할것같아서 미리 `onClick` 필수타입에서 제외 했습니다
- `inputField` 부분에서 새로운 비밀번호는 `autoComplete="new-password"` 값이 들어가야한다고 경고문 뜨길래, 타입 수정했습니다.
> 원래 해놨어야하는건데 제가 js docs에만 작성해두고 추가를 안해뒀더라구요..ㅎㅎ
=> #124 비밀번호 초기화 기능 구현

components/Profile/Profile.tsx, hooks/useFileHandler.ts, hooks/useForm.ts
close #150 
- 프로필 컴포넌트 label 컴포넌트 추가 및 props 추가
- useFilehandler 프리뷰 초기화
- useForm내부에서 파일 에러메세지를 폼 에러메세지에 추가
- InputField 처럼 동일한 label이 필요할 것 같아서 프로필 컴포넌트에도 추가를 했는데 fieldset안에 label이 두개가 있어도 되는지는 모르겠습니다
- 프로필 컴포넌트 디폴트 이미지 일때 bg가 살짝 틀어지는 부분이 있어서 해당 스타일 수정하여, 틀어지지않도록 했습니다
- file input에 대해서 파일 크기에 대한 에러 메세지 노출되도록 추가 하였습니다
- useForm에서 파일 input에 변화가 있을때, 지정된 용량이 넘어가면 프리뷰는 보여주지않고 하단에 에러메세지를 띄웁니다.
=> #150 프로필 컴포넌트 에러메세지 및 라벨 추가

hooks/useUser.ts
close #173 
원래는 `store`에 저장된 `user`와 `useQuery`의 `isPending`을 활용해 리다이렉트 여부를 판단합니다.
하지만 `store`의 `user`와 `useQuery`의 `isPending`은 변경되는 타이밍이 다릅니다.
때문에 `useQuery`로 `data`를 받아와서 `isPending`은 `true`에서 `false`로 변했지만 `user`는 `null`인 타이밍이 존재했습니다.
이 타이밍에 `useUser`가 페이지를 `/`로 리다이렉트 시키는게 에러의 원인이었습니다.
그래서 변경된 코드에서는 `user`를 대신해 `data`를 활용해 리다이렉트 여부를 판단하도록 수정했습니다.
`user`와 `data`는 같은 데이터이므로 기능적인 차이는 발생하지 않을 거 같습니다.
=> 새로고침 시 리다이렉트 되는 문제를 해결

app/boards/ArticleList.tsx, components/ArticleCard/ArticleCard.tsx, components/ArticleCard/ArticleCardContent.tsx, hooks/useGetArticle.ts
close #176 
자유게시판 게시글 삭제 기능 추가했습니다.
자유게시판 게시글 삭제 기능 추가했습니다.
현재 글쓰기 페이지 작업이 아직 병합되지 않아 테스트를 하시려면 직접 게시글 생성 API 요청하여 글 생성하셔서 삭제 테스트를 해보셔야 합니다.
그리고 `article.api.ts`의 API의 경로도(`/article -> /articles`) 수정하셔야 정상 동작합니다.
해당 PR에서 경로를 수정하지 않은 이유는 다른 PR에서 이미 수정을 하고 병합 예정이라 하지 않았습니다. 
되도록 아래 첨부드린 영상 참고하셔서 확인만 부탁드립니다.
https://github.com/user-attachments/assets/d093ac08-34cf-4038-b15f-34e9b83d3cce
=> 자유게시판 리스트 페이지 게시글 삭제 기능

app/(auth)/signup/page.tsx, app/mypage/page.tsx, contexts/DeviceTypeContext.tsx, hooks/useDebounce.ts, hooks/useForm.ts
close #192 
- Input 에러 노출 조건 디바운스 적용(useForm 수정)
- 이름 => 닉네임 통일
- 디바운스 훅, 디바이스 타입 훅 개선
- `useForm` 훅에 `js doc` 추가 했습니다.
- input text 체인지 반영사항과 에러 노출 디바운스 함수 분리하여, 적용했습니다.
- input에 디바운스 적용을 위해서 기존의 `useDebounce`훅을 수정했습니다.
- 이전 코드 : `useEffect` 없이 `callbackRef.current`에 `callback`을 한 번만 할당
- 수정 코드 : `useEffect`로 `callback`이 변경될 때마다 `callbackRef.current = callback`을 갱신
- 개선 이유 : 디바운스된 콜백이 실행되는 시점에 항상 가장 최신의 콜백을 사용해야하는데 이전 코드에서는 콜백이 바뀌어도 `callbackRef.current`가 초기에만 설정된 값 그대로기때문에 옛날 콜백을 사용 할 수 있다는 위험이 있어서 개선함
- 해당 훅을 개선하던 중 기존의 디바이스훅에서 lint에러가 발생해 수정되었습니다
- 결과와 동작에는 큰 차이가 없습니다. 다만, 디바운스 함수와 실제 이벤트 핸들러를 분리한 것 뿐입니다.
- 전체 동작확인은 #191 해당 PR 반영 시 확인 가능합니다
https://github.com/user-attachments/assets/c70570e4-b627-409a-8379-a842015c7223
=> #192 1차 QA 반영 및 input 디바운스 적용

components/Buttons.tsx
close #196 
- 기존버튼에서 loading이 false일때 텍스트 노출
- 링크버튼일때 클릭 영역 확장
- 링크버튼일때 클릭 영역이 너무 좁아서 size-full 추가 했습니다
=> #196 버튼 loading시 로딩스피너만 노출

app/[teamId]/(index)/page.tsx, components/layout/Header/Headers.tsx
close #200 
조건 분기
-  팀 데이터 로딩 중 : 빈 페이지. 로딩 스피너로 변경 예정
-  팀 데이터 불러오기 실패 : 404페이지
-  팀 데이터 불어오기 : 페이지 보여주기
**문제**
팀 데이터 불러오기 실패 시 랜딩 페이지로 리다이렉트 되는데, 원인이 무엇인지는 잘 모르겠습니다.
**해결**
과거 글로벌 네비게이션에 선택된 팀이 없을 때 리다이렉트 시키는 코드를 넣어뒀었는데, 이를 제거했습니다!
=> #200 팀페이지 조건 분기

app/[teamId]/(index)/GroupTaskList.tsx, utils/createUrlString.ts
close #203 
경로와 URL 파라미터가 점점 길어지다 보니 가독성이 떨어지고,
URL 객체의 메스드를 활용하기에도 코드가 복잡했습니다.
그래서 까짓것 유틸 함수 한 개 만들었습니다.
**사용법**
```ts
// 상대 경로 사용법
// /users/123/profile?sort=name&order=asc
const url = createUrlString({
pathname: ['users', 123, 'profile'],
searchParams: { sort: 'name', order: 'asc' }
});
// 절대 경로 사용법
// https://example.com/api/v1/data?limit=10&offset=20
const customUrl = createUrlString({
origin: 'https://example.com',
pathname: ['api', 'v1', 'data'],
searchParams: { limit: 10, offset: 20 }
});
```
`origin` 프로퍼티를 전달하면 절대 경로로 반환되고, `origin`을 전달하지 않으면 상대 경로로 반환합니다.
저희 서비스 내부에서 이동할 경우에는 `origin`을 전달하지 않아도 됩니다.
원래는 `/[groupId]/[taskListId]`로 이동했었는데, 제가 잘 못 설정했습니다.
변경 사항에서는  `/[groupId]/tasklist`를 경로로 설정했습니다.
추가적으로 해당 페이지에서 할 일 목록을 탭으로 이동하던데,
페이지 렌더링 및 URL 공유 시 유용하게 쓰일 거 같아서 `taskList`의 …
=> #203 URL 문자열 생성 함수 구현 및 할 일 목록 이동 경로 수정

hooks/useForm.ts
close #215
`initialValues`의 `key`를 복사해 새로운 객체를 생성하는 함수를 구현했습니다.
**사용법**
```ts
const A = { a : value1,  b : value2  };
const B = initializeValues(A, false);
console.log(B)
// {a : false, b : false}
```
`initializeValues` 함수를 사용해 `changedFields`, `errorMessage`를 초기화 합니다.
기존에는 `useForm` 마운트 시 `changedFields`와 `errorMessage`는 빈 객체인 `{ }`로 초기화 되었습니다.
이는 몇몇 불편한 부분이 있어 이를 개선하기 위해 초기화 로직을 수정했습니다.
=> #215 useForm의 changedFields, errorMessage 초기화 로직 변경

app/[teamId]/(index)/GroupEditModal.tsx, app/[teamId]/(index)/GroupHeader.tsx, app/[teamId]/(index)/TeamPage.type.ts, app/[teamId]/(index)/page.tsx
close #211 
팀 수정하기 기능을 구현했습니다.
팀 페이지에서 `톱니 버튼` -> `수정하기`로 사용 가능합니다.
요구사항에서는 수정하기를 클릭하면 팀 수정하기 페이지로 이동합니다.
하지만 이는 불필요한 리소스 낭비로 느껴저 그냥 팀페이지에서 모달로 팀 수정이 가능하게 구현했습니다.
|![image](https://github.com/user-attachments/assets/63bf50c2-1938-44cc-a57f-5401db9eb557)|![image](https://github.com/user-attachments/assets/69cf2127-feb2-435d-a8e2-b68673c6b5ef)|
|---|---|
|요구사항|변경사항|
=> #211 팀페이지의 팀 수정하기 기능 구현

app/[teamId]/(index)/page.tsx, app/boards/[articleId]/page.tsx, app/boards/editarticle/[articleId]/page.tsx, components/Empty/Empty.tsx, components/layout/Header/Headers.tsx, components/layout/Header/Logo.tsx
close #226 
- ✅ 동적 라우트에서 사용되는 useParams 구조분해할당 한 부분 wrapper로 경고문 해결
- ✅ 로그인 페이지, 헤더에서 발생하는 Image 태그 경고문 해결
- `Headers`, `/[teamId/(index)`, `/boards/[articleld]`, `/boards/editarticle/[articleld]` 해당 페이지에서 `useParams`를 구조분해할당하여 사용하는 부분을 `wrapper`로 감싸서 업데이트 된 리액트에 맞춰 수정 진행했습니다.
- Empty, Logo 컴포넌트에서 발생하는 Image 태그 속성 경고문 수정하여, 해결 하였습니다.
- 리액트가 업데이트 되면서 useParams를 구조분해할당하여 사용하지않고 wrapper로 한번 감싸서 사용하는 방식으로 변경 되었습니다.
- 해당 경고는 다이나믹 라우트에서 발생되는 이슈이며, 앞으로 작업하실때 useParams를 사용하실 일이 있으시다면 wrapper로 감싸서 사용해주시길 바랍니다.
=> #226 useParams 구조분해할당 경고문 및 Image 컴포넌트 경고문 에러 수정

app/(auth)/login/page.tsx, app/(auth)/signup/page.tsx, components/InputField/InputField.tsx, hooks/useForm.ts
close #221 
- 로그인,회원가입 버튼 활성화 조건 변경
- useForm, InputField에 onBlur 핸들러 추가
- useForm에 change 이벤트 발생 여부 상태를 관리하는 함수를 디바운싱과 동기화 시켜, 입력이 완료 된 후에 필드 변경 상태 업데이트를 진행하도록 변경했습니다.
- useForm 훅이 변경되면서 버튼 활성화 조건을 수정하여, 입력이 되지않았을때도 버튼 활성화 되었던 버그 수정했습니다.
- 인풋 필드에 onBlur를 추가하여, 디바운싱 카운트가 끝나기도전에 포커싱 아웃이 되었다면, 디바운스 즉시 중단하도록 수정하여, 에러메세지가 즉시 초기화 되도록 했습니다.
- 재현님께서 남겨주신 https://github.com/fe11-part4-team3/coworkers/issues/221#issuecomment-2648018601 해당 버그는 끝내 확인이 불가능해서, 배포 후 배포 환경에서 추가 테스트 해봐야할것같습니다.
- 우선 이전에 발현되었던 버그는 개선이 되어 PR 올립니다.
=> #221 input 정상 입력 시에도 툴팁이 노출되는 버그 수정

app/[teamId]/layout.tsx
close #240 
저희 백엔드 문제로 팀 멤버가 아닌 사용자가 요청을 보내도 서버가 팀 데이터를 응답으로 보내줍니다.
요청을 막을려면 생각보다 많은 작업이 필요해보입니다. 그래서 해당 작업은 최적화 단계에서 진행하겠습니다.
우선 요청은 보내되, 멤버가 아닐 경우 랜딩 페이지로 리다이렉트 하도록 만들었습니다.
=> 팀페이지에 멤버가 아닌 사용자가 접속이 가능한 문제 해결

app/[teamId]/(index)/GroupDeleteModal.tsx, app/[teamId]/(index)/GroupHeader.tsx, app/[teamId]/(index)/page.tsx, hooks/useTaskLists.ts, service/group.api.ts, types/group.type.ts
close #230 
팀 삭제하기 기능을 구현했습니다.
팀 삭제 이후는 마땅히 이동할 위치를 모르겠어서 랜딩페이지로 이동하게 만들었습니다.
더 좋은 의견이 있으시다면 언제든 말씀 부탁드립니다.
모달 같은 경우, 시간에는 삭제와 관련된 모달이 없어서 @JUYOUNG0728 님이 만들어 두신 회원 탈퇴 모달 코드를 긁어와 만들었습니다.
=> #230 팀 삭제하기 기능 구현

app/boards/ArticleList.tsx
close #244 
자유게시판 리스트 페이지 테블릿, 모바일 해상도에서 게시글 카드 배열이 틀어지는 현상 수정하였습니다.
=> 자유게시판 리스트 페이지 테블릿, 모바일 해상도 UI 틀어짐 수정

app/[teamId]/(index)/DeleteTaskListModal.tsx, app/[teamId]/(index)/EditTaskListModal.tsx, app/[teamId]/(index)/GroupTaskList.tsx, app/[teamId]/(index)/GroupTaskListWrapper.tsx, app/[teamId]/(index)/page.tsx, components/DropDown.tsx, components/modal/AddTaskList.tsx, stories/modal.stories.tsx
close #232
다음 기능들에 고용 모달을 적용합니다.
- 할 일 목록 생성
- 할 일 목록 수정
- 할 일 목록 삭제
추가적으로 할 일 목록의 드롭다운 컨텐츠 클릭 시 할 일 목록 상세로 이동되는 이슈가 있었는데
해당 이슈에서 위 문제를 해결했습니다.
기존 @junghwaYang 님이 구현하신 `DropDown` 컴포넌트에 `ref` props를 추가했습니다.
`ref` props는 드롭다운의 컨텐츠를 가리킵니다.
사용자가 요소를 클릭 할 때 `event.target`이 `ref.current` 내부의 요소의 경우 드롭다운을 클릭했다고 판단해
요소의 상세 페이지로 이동하지 않도록 구현했습니다.
=> #232 모달이 없던 기능들에  공용모달 적용

app/[teamId]/tasklist/page.tsx, hooks/useTaskLists.ts, stories/modal.stories.tsx
Closes #289 
---
- ✅ group id를 받아오던 로직을 useGroup의 groupId 프로퍼티로 대체
- ✅ 할 일 목록을 받아오던 로직을 useTaskList로 대체
- ✅ 할 일 목록 탭 이동 경로 수정
=> #289 할 일 리스트 페이지 커스텀 훅 적용

app/(auth)/reset-password/page.tsx, app/(auth)/signup/page.tsx, components/modal/ChangePassword.tsx, hooks/useForm.ts, hooks/useInputFieldHandler.ts, utils/validation.ts
Closes #305  
---
- ✅ **[validation]** 조건 수정
- ✅ **[회원가입, 패스워드 변경]** 별도의 onChange 이벤트 및 에러메세지 추가
---
---
- useForm내부에서 해당 비밀번호, 비밀번호 확인에 대해서 같이 작성을 하려했으나, 디바운싱 적용이 안되고, 비밀번호를 입력할때마다 검증을 하길래 별도 페이지로 뺐습니다.
- 우선 기능 구현 완료를 위해서 페이지 별로 별도 작성을 해두었는데 시간이 될때 리팩토링으로 useForm내부에서 검증진행하도록 하겠습니다
- 현재 reset-password 페이지가 진입하는 즉시 메인으로 리다이렉트 되는데 useUser 내부에서 강제 리다이렉트 시키는 것 때문에 해당 페이지 접속이 안되는것같습니다 @Woolegend 님 2차QA때 남겨두었던 사항이라 우선 비밀번호,비밀번호 확인 필드가 들어가있는 페이지에는 전부 동일한 조건 추가 했습니다.
- 그래서 회원가입과 비밀번호 변경 모달에서 변경된 검증 테스트 가능합니다.
=> #305 2차QA 14번 이슈 수정 - 비밀번호,비밀번호확인 정상 입력후 다시 비밀번호를 변경할때 버튼활성화 되는 이슈

app/[teamId]/tasklist/TaskListWrapper.tsx, app/[teamId]/tasklist/page.tsx, components/ui/drawer.tsx, package-lock.json, package.json, tailwind.config.ts, utils/validation.ts
Closes #303 
---
- ✅ **할 일 상세 컴포넌트에 ShadCN drawer 컴포넌트 적용**
- ✅ **할 일 상세에서 댓글 작성 기능 구현**
- ✅ **할 일 상세 관련 API 바운더리 재설정**
- ✅ **text-t-secondary 설정**
---
✔ **할 일 상세에 drawer 적용으로 인해 사용자 경험 향상**
✔ **할 일 목록 불러오기 시 useTaskLists 사용으로 인해 불필요 요청 감소**
✔ **API 바운더리 명확하게 변경해 코드 가독성 향상**
---
---
- 할 일 상세 레이아웃은 기조의 @JUYOUNG0728 님이 구현해 주신 것을 거의 그대로 사용했습니다.
- text-t-secondary 색상이 정의가 안 되어 있었는데 이제 발견했습니다 ㅋㅋ!
=> #303 할 일 상세 컴포넌트 개선

app/boards/editarticle/[articleId]/page.tsx, components/ImageUpload/ImageUpload.tsx, hooks/useFileHandler.ts, reducer/formReducer.ts, types/useForm.type.ts, utils/updatePayload.ts
Closes #304 
---
- ✅ 게시글 수정 페이지에서 등록된 게시글 이미지가 `Preview`로 노출되도록
- ✅ `useForm` 관련 코드 수정(이미지가 없는 경우 빈 값이 아닌 `null`로 저장되도록)
---
---
`useForm` 관련 코드에서 `image`가 업로드되지 않았을 때 빈값이 아닌 `null` 값으로 `formData`에 저장되게 수정했습니다.
빈값에서 `null` 값으로 변경한 이유는 게시글 `PATCH` 할 때 `image`가 등록되지 않았을 때 빈값이 아닌 `null` 값으로만 요청을 받아 수정하게 되었습니다.
업로드 기능이 있는 다른 페이지 테스트는 진행하여 문제없는 것을 확인했습니다.
=> 게시글 수정페이지 Preview 미노출 이슈

app/[teamId]/tasklist/page.tsx, components/DateTimePicker/DatePicker.tsx, components/modal/AddTask.tsx, components/ui/calendar.tsx, hooks/useDate.ts, hooks/useToggle.tsx
Closes #315 
---
- ✅ **[할일 리스트 캘린더]** 구현 완료
- ✅ **[DatePicker 컴포넌트]** 재사용성을 위해 필드 분리
- ✅ **useDate** 요일 한국어 패치 완료
- ✅ **useToggle 훅** 생성
---
✔ **사용자 경험 개선**: [기능 추가로 인해 사용성이 향상됨]  
✔ **퍼포먼스 최적화**: [단순 토글 기능에 대한 함수를 훅으로 분리하여 전역으로 사용가능(재사용성 증가)]
---
---
- 기능 구현이 적절한지 검토 요청
=> #315 할일 리스트 캘린더 추가

components/layout/Header/HeadersProfileDropDown.tsx
Closes #323 
---
- ✅ **드롭다운 클릭 후 닫히지 않는 문제 해결**
`DropDown` 컴포넌트의 `href` 속성으로 기능을 설정한 경우 아이템을 클릭 후 드롭다운이 닫히지 않는 문제가 있습니다.
그래서 `onClick`을 활용해 경로를 이동하도록 드롭다운의 `items`를 수정했습니다.
=> #323 드롭다운 클릭 후 닫히지 않는 문제 해결

app/(auth)/layout.tsx, components/InputField/HideToggle.tsx, components/layout/Container.tsx
Closes #318 (← 여기에 이슈 번호 입력)
---
- ✅ **[모바일 UI 가운데로 ]** 구현 완료
- ✅ **[애니메이션 className w-full]** 추가
---
✔ **사용자 경험 개선**: [모바일에서는 컨텐츠가 얼마없는 화면을 가운데로 보이게 개선]  
---
---
=> #318 팀참여,팀생성,로그인,패스워드 재설정

components/DateTimePicker/DatePicker.tsx, components/modal/AddTask.tsx
Closes #327
---
- ✅ **[이전날짜 클릭 시 스낵바 노출]** 구현 완료
- ✅ **[할일 리스트 달력 클릭 시 ]** UI 개선
---
✔ **사용자 경험 개선**: [할일 생성 시 이전날짜는 선택 불가]  
✔ **UI 개선**: [할일 리스트에서 달력 클릭 시 너무 멀어지지않게 개선]
---
---
=> #327 할일 추가 모달에서 이전 날짜 선택 시 경고 스낵바 추가

app/page.tsx, components/Landing/LandingCardItemsthird.tsx, styles/base.css, tailwind.config.ts
Closes #329 (← 여기에 이슈 번호 입력)
---
- ✅ **[모바일 랜딩 하단 bg 컬러]** 시안에 맞게 수정
- ✅ **[랜딩 bg 컬러]** 추가
- ✅ **[랜딩 3번째 item 라이트모드]** 적용
---
---
- 세번째 컨텐츠의 경우 피그마 디자인시스템에 명시된게 없어서 #fff에서 살짝 어두운 계열로 잡아두긴했는데 모니터 환경에 따라 안보일수도있습니다. 이부분을 어떻게 해야할지 의견주세요
- 확인하다보니 item 2,3번째는 box-shadow가 포함되어있지않은것같아서 이거는 랜딩 리팩토링 하면서 추가하겠습니다
=> #329 메인 랜딩 QA 반영(bg컬러 및 라이트모드)

app/[teamId]/(index)/GroupReportContent.tsx, app/boards/BestArticleList.tsx, app/page.tsx, components/ArticleCard/ArticleCard.tsx, components/Indicators.tsx, components/Landing/LandingCard.tsx, styles/base.css
Closes #340 
---
- ✅ 다른 서브 페이지와 동일하게 랜딩 페이지 접속 시 애니메이션 적용
https://github.com/user-attachments/assets/7092fe96-b31b-4d31-b1fb-e5ee8b0c3e99
- ✅ 메인 `Visual` 이미지 좌우로 움직이는 `keyframe` 적용
https://github.com/user-attachments/assets/5b5f5cc7-550c-4e8a-a9b4-bad3867e1cfe
- ✅ `LandingCardList` 페이지 애니메이션 적용
https://github.com/user-attachments/assets/aa80a850-e136-4246-b7b6-2c7f1905d122
- ✅ 인디케이터 재사용 가능하도록 컴포넌트 분리
- ✅ 자유게시판 리스트 페이지 인디케이터 적용 (모바일만 적용하니 데스크탑도 추가되는 것이 좋은 것 같아서 전체 해상도에 적용했습니다.)
- ✅ 팀 리스트(리포트) 기존 인디케이터를 공통 인디케이터 적용
---
수정 요청 주신 자유게시판 스와이프 기능은 적용이 안 되어 있는 줄 알았는데 이미 적용이 되어 있어서 별다른 작업하지 않았습니다.
=> 💄 랜딩페이지 애니메이션 적용 및 자유게시판, 팀 리스트 케러셀 인디케이터 추가, 수정

app/[teamId]/(index)/page.tsx
Closes #346 
---
- ✅ useParam로 받아온 groupId를 요청 시 사용하도록 변경
=> #346 팀페이지의 할 일 목록을 요청 시 undefined가 groupId로 전달되는 문제 해결

app/[teamId]/(index)/GroupTaskListWrapper.tsx, app/[teamId]/(index)/page.tsx
Closes #347 
---
- ✅ **할 일 목록이 6개를 초과할 경우 더보기 기능을 사용할 수 있습니다.**
- ✅ **할 일 목록이 응답 순서가 아닌 생성된 순서로 정렬됩니다.**
- ✅ **생성된 할 일 목록이 존재하지 않을 경우 특정 문구를 출력합니다.**
- ✅ **팀 페이지 하단 마진 추가**
---
=> #347 팀페이지 더보기 기능 구현

app/[teamId]/tasklist/TaskDetail.tsx, app/[teamId]/tasklist/page.tsx, app/boards/ArticleList.tsx, app/layout.tsx, app/page.tsx, components/Empty/Empty.tsx
Closes #351 
---
- ✅ 랜딩페이지 tablet, mobile keyframe 애니메이션 적용
- ✅ 메타태그 추가 (mobile에서 input 클릭 시 화면 확대되는 이슈)
- ✅ 할 일 리스트 날짜 변경 버튼 여러번 클릭 시 하단 텍스트 드래그 되는 현상 수정
- ✅ 자유게시판 정렬 기능 시 스크롤 위치 변하는 이슈 수정
- ✅ 할 일 상세 수정 input, textarea placeholder 적용
---
랜딩 페이지의 최상단 백그라운드 이미지가 움직이는 모션의 경우, 아예 제거를 해버릴까 했는데 또 막상 없으면 너무 허전한 것 같아서 우선은 tablet, mobile 해상도 둘 다 적용하는 것으로 결정했습니다.
혹시나 확인해보시고 없는게 더 낫다고 생각드시는 분이 계시다면 말씀 부탁드릴게요 ㅜㅜ 저도 잘 모르겠어서 일단은 추가했습니다..😅
해당 이슈의 경우 정렬을 바꾸는 순간 스켈레톤이 노출되는데 스켈레톤의 갯수가 적어서 그에 맞는 페이지 높이?가 순간 변경되어 스크롤 위치가 달라지는 것 같아서 스켈레톤 갯수를 늘려 해결하였습니다. tablet, mobile에서도 확인했습니다.
---
하나의 PR에 지금 수정된 내용이 많아보이는데 코드 수정이 한 줄씩 밖에 수정이 되지 않아 리뷰함에 있어서 문제가 없을 것 같다고 판단되어 하나의 PR에 올렸습니다.
혹시나 불편하신 분들 계시다면 양해 부탁드립니다..🥲
=> 랜딩 애니메이션 모바일 적용 및 메타태그 추가

components/Comment/Comment.tsx, types/inputField.type.ts
Closes #353 
---
- ✅ 댓글 컴포넌트 수정 시 textarea focus 적용하였습니다.
댓글 수정 시 textarea focus되며, 댓글 문자열 가장 뒤에 커서가 생기도록 작업하였습니다.
https://github.com/user-attachments/assets/53a900cb-048b-49f8-adc0-a8fed3f80c40
https://github.com/user-attachments/assets/7db06d62-3a33-47d7-b15c-98f02d8460b2
=> 📝 댓글 컴포넌트 수정 시 textarea focus 적용

app/(auth)/login/page.tsx, components/OauthForm.tsx
Closes #362
---
- ✅ **[Oauth Form ref]** 제거
- ✅ **[로그인 자동완성 버튼 활성화]** 안됐던 문제 수정
---
✔ **이슈 개선**: [로그인 기능 원복]  
---
---
- 생각해보니 배포 하고나서는 소셜 로그인 확인을 제대로 못했었는데, 개발 모드에서 정상적으로 로딩 없이 진행되었던 방식이 ref를 넣기 전 버전이었던것같아서 ref 제거 한 채로 배포 부탁드립니다.
- 원래는 중복호출을 막고자 한건데 혹시나 싶어서 테스트 배포 부탁드립니다
=> 🔨 oauthForm 컴포넌트 ref 제거

components/NavigationGroupDropdown/DropdownAddGroup.tsx, components/NavigationGroupDropdown/DropdownTab.tsx, components/NavigationGroupDropdown/NavigationGroupDropdown.tsx, components/layout/Header/HeadersGnb.tsx
Closes #358
---
- ✅ 드롭다운에 선택된 팀의 프로필 이미지 표기
- ✅ 드롭다운 아이템에 cursor-pointer 적용
=> #358 네비게이션 드롭다운에 선택된 팀의 프로필 이미지 표기
