components/DropDown.tsx

fix #70 
- 드롭다운 컴포넌트 텍스트 사이즈 추가
- 드롭다운 아이템에 폰트 스타일이 적용되어있지않아서 폰트 스타일 추가했습니다

드롭다운 item 텍스트 추가

---

components/SearchInput/SearchInput.tsx
components/ui/toast.tsx
components/ui/toaster.tsx
hooks/use-toast.ts
public/images/icon-search.svg
stories/SearchInput.stories.tsx

close #72 
- 검색 Input 추가
- 스토리북 추가
- 자유게시판에서 사용되는 검색 Input 작업 완료했습니다.
- 스토리북에서 확인하실 수 있게 추가했습니다.

자유게시판 검색 Input

---

.github/workflows/create-branch.yml
.vscode/settings.json

close #62 
기존의 목표였던 tailwind CSS intellisense가 다시 잘 동작합니다.
몇 일 동안 suggestion이 먹통이라 lint와 충동 문제일지 알고 골머리를 썩었는데,
원인은 VSCode의 메모리 문제였습니다.
해결 방법은 불필요한 메모리 사용을 제한해 intellisense에 할당 될 수 있는 메모리의 확보입니다.
대상이 되는 경로는 저희가 직접 수정을 하지 않는 파일을 기준으로 잡았습니다.
- node_modules
- .dist
- .git
- .next
파일 탐색기와 검색에서는 안 보이지만 개발에는 문제가 없으니 안심하셔도 됩니다!
파일 탐색기에서 특정 경로를 숨깁니다.
파일 탐색기에서는 안 보이지만 실제 개발에는 영향을 끼치지 않습니다.
```json
"files.exclude": {
"**/node_modules": true,
"**/dist": true,
"**/.git": true,
"**/.next": true
},
```
검색할 필요가 없는 파일을 검색 대상에서 제외합니다.
메모리와는 크게 상관없지만 검색 가독성과 속도가 증가한다고 합니다.
```json
"search.exclude": {
"**/node_modules": true,
"**/dist": true,
"**/.next": true
},
```
파일 탐색기가 특정 경로를 감시하지 않도록 하는 설정입니다.
실시간 탐지하는 대용량 파일이 줄어들기 때문에 에디터의 과부하를 방지합니다.
실제로 확인 결과 CPU와 메모리의 사용이 감소한 것을 확인했습니다.
```json …
```

VSCode 최적화 및 브랜치 생성 액션 수정

---

app/globals-custom.css

close #87 
- shadcn의 border-input class로 덮어씌워지고있어서 border 적용이 안되었음
- globals-custom.css에서 border color 변경
- shadcn border-input class 덮어쓰기

globals-custom border 값 수정

---

components/layout/Header/Headers.tsx

close #130 
로그인 하시면 바로 테스트 해 보실 수 있습니다!
로그아웃 기능은 기존 @junghwa1996 님이 만들어 주신 것을 사용했습니다.
제 기억에는 작업하시던 모달의 z-index가 50이었던 거 같아
네비게이션은 그 보다 한 단계 적은 40으로 설정했습니다.
혹시 모달의 z-index가 50보다 크다면 말씀해주세요!

#130 네비게이션의 유저 드롭다운 구현

---

app/boards/AddArticleButton.tsx
app/mypage/page.tsx
components/ArticleCommentTextarea/ArticleCommentTextarea.tsx
components/Buttons.tsx
components/Comment/CommentFooter.tsx
components/InputField/InputField.tsx
types/buttons.type.ts

close #148 
- 버튼 컴포넌트 props width => className
- 작업을 하다보니 버튼 컴포넌트에 바로 className을 주어서 스타일링하는게 사용하시는 분들께도 편할 것 같아서 재 수정하였습니다.
- 여러번 번복 수정 죄송합니다 🥲
- 버튼 컴포넌트에서 href를 사용하여 Link를 변환 할 경우 icon과 같이 사용하게 되면 디자인이 틀어지는 경우가 발생하여, Link일때도 디자인이 틀어지지않도록 조정했습니다.
- icon이 있을때 마진 추가 되었습니다
- 기본적으로 width, margin 정도만 받기 위해서 추가했습니다. 그 외의 스타일 수정은 공통 스타일을 해치기 때문에 두가지 속성만 사용 부탁드립니다.

#148 버튼 컴포넌트 props 수정

---

components/layout/Container.tsx

close #152 
- Container 컴포넌트 스타일 변경
- 페이지 전체에 공통으로 사용하는 컴포넌트이다보니 빠른 반영을 위해서 나눠 올립니다
- 기존에는 패딩으로 상단 header와 겹치지않게 밀어줬는데 그렇게 되면 내부 컴포넌트에서 상단 값을 조정해주기가 쉽지않아서 마진으로 변경했습니다.
- 컨텐츠 상단 값 조정하실때는 패딩을 사용하시면 됩니다.
- 이미 작업 하신 분이 있으시다면 수정 부탁드립니다

#152 Container 컴포넌트 pt에서 mt으로 변경

---

app/[teamId]/(index)/GroupTaskList.tsx

close #160 
할 일 목록 클릭 시 해당 할 일 상세 페이지로 리다이렉트 하는 기능 구현했습니다.
코드가 간단한지만 다른 PR에 낑구기 애매해서 따로 PR 올렸습니다.

 #160 팀페이지 할 일 목록 클릭 시 리다이렉트 구현

---

app/boards/[articleId]/ArticleDetail.tsx
app/boards/addarticle/page.tsx
app/boards/editarticle/[articleId]/page.tsx
components/ArticleCard/ArticleCardContent.tsx
components/InputField/TextareaField.tsx
hooks/useForm.ts
hooks/useGetArticle.ts
utils/updatePayload.ts

close #178 
자유게시판 게시글 수정 페이지 작업 완료했습니다.
- 게시글 수정 페이지 작업 완료했습니다.
- 수정 버튼의 경우 제목, 내용, 이미지 중 하나라도 변경되지 않는 경우 수정 버튼 비활성화 되도록 하였습니다.

자유게시판 게시글 수정 페이지

---

app/mypage/page.tsx
components/ArrowTooltip.tsx
components/InputField/ErrorMessage.tsx
components/InputField/InputField.tsx
components/Profile/Profile.tsx
hooks/useFadeComponents.ts
stories/ArrowTooltip.stories.tsx
stories/InputField.stories.tsx
styles/components.css
tailwind.config.ts

close #190 
- 화살표 툴팁 제작
- input 컴포넌트에 화살표 툴팁 연결
- 화살표 툴팁 컴포넌트 제작 했습니다
- fadeIn, fadeOut 컴포넌트 마운트를 메세지 텍스트 기반으로 체크하여 애니메이팅 진행하는 훅과 tailwind class 추가 하였습니다.
- 사용 시 Input에서 사용되는 방식을 참고해주세요
- 해당 툴팁은 기본적인 위치값은 정해져있지않습니다. 
> 나중에 위로 표시되는 툴팁도 필요할 경우 추가 확장으로 제작 할 예정
- ArrowTooltip 컴포넌트 확장하여 별도의 툴팁으로 위치값 설정
- useFadeMessage훅 호출
```ts
const { fadingMessage, animationClass } = useFadeMessage(message);
```
조건 설정(필요 시)
```ts
const errorMessageState = (errorMessage: string) => {
if (
errorMessage === '이메일은 필수 입력입니다.' ||
errorMessage === '비밀번호는 필수 입력입니다.' ||
errorMessage === '닉네임은 필수 입력입니다.' ||
errorMessage === '팀 이름은 필수 입력입니다.'
) {
return 'ERROR';
} else {
return 'WARNING';
}
};
```
예제
```tsx
{fadingMessage && (
<ErrorMessage
tooltipState={errorMessageState(fadingMessage)}
className={animationClass}
> …
```

#190 화살표 툴팁 제작

---

components/layout/Header/Headers.tsx
components/modal/Logout.tsx
stories/modal.stories.tsx

close #205
현재 로그아웃 시 그룹 데이터와 할 일 목록 데이터를 지우지 않는 문제가 있었는데
해당 이슈에서 이를 해결했습니다.
아마 할 일 데이터와 게시글 데이터도 비슷한 문제가 있을 듯 합니다.
추가적으로 주영님께서 구현해주신 공용 모달도 잘 사용했습니다.

#205 로그아웃 시 스토어 및 캐싱 지우기

---

app/myhistory/mock.json
app/myhistory/page.tsx

close #207 
- 마이히스토리 UI 작업
- 마이히스토리 UI 스타일링 작업 진행 했습니다.
- 기능은 @Gwanhoo 님께서 작업해주실 예정 입니다.
- 폼이 크지않아서 금방 작업 되었습니다
- @hwiiron 님 컴포넌트 잘 사용했습니다! 👍🏻

#207 마이히스토리 페이지 UI 작업

---

components/SideNavigation/SideNavigation.tsx

close #212 
부끄럽지만 또 오타 문제입니다.
제가 초기에 셋업했던 작업 중 오타가 너무 빈번하네요
다시 한 번 사죄드립니다.

#212 사이드 네비게이션 자유게시판 경로 수정

---

app/[teamId]/(index)/GroupMemberList.tsx
components/modal/InviteMember.tsx
stories/modal.stories.tsx
utils/createUrlString.ts

close #231 
멤버 초대하기 기능을 구현하고 공용 모달을 적용합니다.
클립보드에 링크를 복사하는 부분을 보면 `setTimeout`으로 랩핑되어 있습니다.
```ts
setTimeout(() => navigator.clipboard.writeText(path), 500);
```
해당 부분은 clipboard api 관련 오류를 해결하기 위한 처리입니다.
자세한 내용은 아래를 참고해주세요
> [[Javascript] confirm 후 clipboard api 사용 시 DOMException Error 발생하는 문제점](https://ramincoding.tistory.com/entry/React-confirm-%ED%9B%84-clipboard-api-%EC%82%AC%EC%9A%A9-%EC%8B%9C-DOMException-Error-%EB%B0%9C%EC%83%9D%ED%95%98%EB%8A%94-%EB%AC%B8%EC%A0%9C%EC%A0%90)

#231 멤버 초대하기 기능 구현

---

components/SideNavigation/SideNavigation.tsx
components/layout/Header/Headers.tsx
components/layout/Header/HeadersGnb.tsx
components/layout/Header/HeadersProfileDropDown.tsx
components/layout/Header/HeadersSideNav.tsx
components/layout/Header/Logo.tsx
components/layout/Header/Profile.tsx

close #254 
- 헤더 컴포넌트 수정
- 헤더 컴포넌트 내부에 작성되어있던 gnb, profile, sidebar 컴포넌트로 분리했습니다.
- 시안에 맞게 조건 추가하였습니다 (로그인,회원가입 삭제) 
- @Woolegend 사이드바 스타일링은 따로 작업하진않았습니다 조건만 추가했으니 확인 부탁드립니다~

#254 헤더 디테일 수정 및 리팩토링

---

app/[teamId]/tasklist/page.tsx

---
name: Feature request
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''
---
Closes #286 (← 여기에 이슈 번호 입력)
---
- ✅ **[UI/UX]** 수정 완료
---
---

#286 => #284 할일 추가 버튼 수정

---

components/DateTimePicker/DatePicker.tsx
components/DateTimePicker/RecurringDay.tsx
components/SelectBox.tsx
components/modal/AddTask.tsx
hooks/useForm.ts
hooks/useTaskLists.ts
hooks/useTaskMutation.ts
stories/DatePicker.stories.tsx
types/useForm.type.ts
utils/updatePayload.ts

Closes #288 (← 여기에 이슈 번호 입력)
---
- ✅ **[POST 뮤테이션으로 최적화]** 완료
- ✅ **API 연동** 적용
- ✅ **DatePicker** 부모요소로 데이터 전달 함수 적용
- ✅ **주반복 클릭 시** 반복할 요일 토글 기능 추가, 배열로 데이터 전달 완료
- ✅ **값 선택 없을 경우** 기본값으로 formData 전달
- ✅ **API 요청 함수** 조건에 따른 요청 설정 완료
- ✅ **timePicker** 받는 데이터가 없어서 삭제
- ✅ **useForm** date와 number[] 을 받기 위해 타입 추가
- ✅ **useForm** 기본 input 외 date 및 셀렉트를 받기위해 setForm 리턴값 지정
---
---
- 기능 구현이 적절한지 검토 요청

#288 => #284 AddTask 모달 API POST 및 DatePicker 수정

---

app/[teamId]/(index)/page.tsx
app/[teamId]/tasklist/page.tsx
components/modal/AddTask.tsx
hooks/useDate.ts
hooks/useTaskLists.ts
hooks/useTaskMutation.ts
stores/useDateStore.ts

Closes #296
---
- ✅ useDateStore 구현
- ✅ useDateStore을 관리하기 위한 useDate 커스텀 훅 구현
- ✅ 할 일 모달 렌더링 시 불필요한 할 일 목록을 요청하는 오류 해결
- ✅ 팀 페이지에서 초기 할 일 목록을 불러오지 못하던 오류 해결
- ✅ useTaskLists 리팩토링

#296 할 일 추가 모달 렌더링 시 불필요한 요청을 보내던 오류 해결

---

components/Comment/CommentFooter.tsx

Closes #301 
---
- ✅ 댓글 수정하기 버튼 텍스트 색상 추가

💄 댓글 수정하기 버튼 텍스트 색상 추가

---

components/OauthForm.tsx
components/modal/ChangePassword.tsx
service/auth.api.ts
service/axios.ts
stores/useUser.store.ts
utils/updatePayload.ts

Closes #299 
---
- ✅ 불필요한 **console.log** 제거
- ✅ **alert** 스낵바로 교체
---

#299 2차QA alert 스낵바로 교체

---

app/[teamId]/tasklist/TaskListWrapper.tsx
app/[teamId]/tasklist/page.tsx

close #312
- 할일 리스트 > 할일 만들기 버튼 위치 수정
- 할일 리스트 데이터 없을때 추가
- 할일 만들기 버튼이 초기렌더 때 상단으로 잠시 노출되었다가 하단으로 내려가는 현상 수정했습니다
- 할일 리스트 없을때 Empty 컴포넌트 활용해서 노출하도록 수정했습니다

#312 할일 리스트 2차 QA 반영

---

app/[teamId]/(index)/GroupHeader.tsx
app/[teamId]/(index)/GroupMemberCard.tsx
app/[teamId]/(index)/GroupTaskList.tsx

Closes #325 
---
- ✅ 헤더 드롭다운 트리거
- ✅ 힐 일 목록 카드
- ✅ 멤버 목록 카드

#325 팀페이지 상호작용 요소 cursor pointer 설정

---

components/DateTimePicker/DatePicker.tsx
components/modal/AddTask.tsx
hooks/useToggle.tsx

Closes #333 
---
- ✅ **[주반복 최소1개이상선택 시 submit 가능하게]** 구현 완료
- ✅ **[캘린더 외부 입력 시 닫힘]** 추가
---
✔ **사용자 경험 개선**: [기능 추가로 인해 사용성이 향상됨]  
---
---
- 기능 구현이 적절한지 검토 요청

#333 주반복 최소1개이상선택 및 캘린더 외부클릭시 닫힘기능

---

app/[teamId]/tasklist/page.tsx
components/SideNavigation/SideNavigation.tsx

Closes #331 
---
- ✅ **[사이드바 close]** 아이콘 수정
- ✅ **[사이드바 그룹 리스트 ]** gap 제거
- ✅ **[할일 추가 아이콘]** 게시글 작성과 동일하게 수정
---
✔ **UI 개선**: [아이콘 UI 개선]  
---
---

#331 사이드바 및 할일 추가 버튼 icon 수정

---

app/boards/[articleId]/CommentContainer.tsx

Closes #336 
---
- ✅ 게시글 상세 댓글 작성 시 실시간 댓글 수 업데이트

✨ 게시글 상세 댓글 작성 시 실시간 댓글 수 업데이트

---

app/[teamId]/(index)/GroupMemberCard.tsx

Closes #345 
---
- ✅ **팅장 멤버 카드의 드롭다운 제거**
---

#345 팀장 멤버 카드의 드롭다운 제거

---

README.md

Closes #355 
---
- ✅ README 작성
이전 팀에서 제가 작성했던 README 참고하여 내용만 변경해서 간단하게 작성했습니다.
내용 수정하거나 추가되었으면 좋겠다고 생각하시는 부분있다면 말씀 부탁드립니다.

📝 README 작성

---

components/Profile/Profile.tsx

Closes #357  (← 여기에 이슈 번호 입력)
---
- ✅ 이미지 가운데 정렬 및 리사이즈

#357 프로필 컴포넌트 이미지 리사이즈 및 가운데 정렬

---

app/(auth)/login/page.tsx
app/(auth)/signup/page.tsx

Closes #123 (← 여기에 이슈 번호 입력)
---
- ✅ 회원가입 페이지 리다이렉트 경로 수정
- ✅ 로그인 페이지 리다이렉트 경로 수정
---

#369 로그인/회원가입 페이지 리다이렉트 경로 수정

---

app/[teamId]/tasklist/TaskDetail.tsx
components/TaskCard/TaskCard.tsx

Closes #364 
---
- ✅ 할 일 카드, 할 일 상세 시간 제거하였습니다.

💄 할 일 카드, 할 일 상세 시간 제거

---

app/(auth)/login/page.tsx
components/OauthForm.tsx

Closes #371 
---
- ✅ **[oauthForm]** 세션 상태 추가
---
---
- 디버깅을 위해서 세션 상태 log를 추가했습니다
- 배포 후 확인이 필요합니다
- 세션의 상태를 이용해 안전하게 세션 정보가 있을때, 조건을 추가했습니다.

🔨 세션 상태 조건 추가(디버깅을 위해 console.log 추가)

---

hooks/useKakao.ts

Closes #373  (← 여기에 이슈 번호 입력)
---
- 카카오 로그인 후 강제 로그인페이지로 리다이렉트

🐛 카카오 로그인 후 강제 로그인페이지로 리다이렉트

---

app/(auth)/login/page.tsx
components/Landing/LandingCard.tsx

Closes #375 
---
- ✅ **일반로그인** 리다이렉트 안되는 문제 수정
- ✅ **랜딩 아이템** 이미지 크기 다른부분 수정
---
---
- 기능 구현이 적절한지 검토 요청

🔨 일반 로그인 리다이렉트 수정

---

app/myhistory/page.tsx

Closes #377  (← 여기에 이슈 번호 입력)
---
스켈레톤 이미지 배치 수정했습니다. 
승인 부탁드립니다.

스켈레톤 이미지 배치 코드 수정

---

app/[teamId]/(index)/GroupHeader.tsx
app/[teamId]/(index)/page.tsx
app/[teamId]/tasklist/page.tsx

Closes #379 
---
✅ 모든 의존성이 채워지지 않은 hook
✅ 할 일 목록 삭제 시 리포트에 변경 사항이 반영되지 않는 문제
✅ 불필요한 주석 제거
✅ 할 일 리스트 페이지에 팀으로 돌아가기 버튼
✅ 할 일 리스트 페이지의 할 일 목록 탭 정렬
✅ 팀 헤더 썸네일이 select 되는 문제
✅ 모바일 사이즈에서 팀 헤더의 제목과 썸네일의 레이아웃이 충돌하는 문제

#379 QA 사항 반영
